service: v1-service
org: rowell
app: serverless-extensions

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-east-1:295279419433:layer:lambda-logs:14
