service: v1-service
org: rowell
app: serverless-extensions

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
    layers:
      - arn:aws:lambda:us-east-1:295279419433:layer:lambda-logs:48

  logs:
    handler: handler.logs
    events:
      - http:
          path: /logs
          method: post

