service: v1-service
#org: rowell
#app: serverless-extensions

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    AWS_LAMBDA_EXEC_WRAPPER: /opt/lambda-logs-extension/wrapper

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
    layers:
      - arn:aws:lambda:us-east-1:295279419433:layer:platform-extension:7

  logs:
    handler: handler.logs
    events:
      - http:
          path: /logs
          method: post

